<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_State</name>
   <tag></tag>
   <elementGuidId>75afb692-61a9-4e75-84e6-4bd3e8625e6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>state_dd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='state_dd']</value>
   </webElementProperties>
</WebElementEntity>
